#Z-score outliners

In [ ]:
dataframe =pd.DataFrame( {'X1': [155,15,13,11,12,20,15,156,13,10,12, 10],

       'X2': [149,169,126,148,155,162,189,555,147,150,153, 655]})
dataframe.describe()

In [ ]:
def outliers_detector(dataframe):
  flag = -1
  outliner=[]
  for col in dataframe:
    flag +=1
    zscores = stats.zscore(dataframe[col])
    ind = np.where(zscores>2)[0]
    indlist = ind.tolist()
    outliner =outliner+( list(zip(ind, flag*np.ones(len(indlist), np.int64))))
  return outliner

In [ ]:
outliers_detector(dataframe)

[(0, 0), (7, 0), (11, 1)]

# sortowanie z pivotami

In [ ]:
import statistics as st
import math as m

def modifiedQuickSortIndicators(stockPrices):
    
    if (all(x<=10**9 and x>0 for x in stockPrices)):
      if len(stockPrices)>=3 and len(stockPrices)<=10**5:
        if len(stockPrices)<=3:
          sequence = sorted(stockPrices)
          return sequence
        else:
          pivot =  st.median([stockPrices[0], stockPrices[m.floor(len(stockPrices)/2)],stockPrices[len(stockPrices)-1]] )
          left_arr = [i for i in stockPrices if i < pivot]
          right_arr = [i for i in stockPrices if i > pivot]
          print (pivot) #jesli return, to tylko pierszy call
          modifiedQuickSortIndicators(left_arr)
          modifiedQuickSortIndicators(right_arr)
          
    

In [ ]:
stockPrices = [5, 2, 3, 16, 1, 4]

In [ ]:
modifiedQuickSortIndicators(stockPrices)

5
2


#sumowanie cyfr z id

  1 -> 1
  2 -> 11 -> jedna jedynka
  3 -> 21 -> dwie jedynki
  4 -> 1211 -> jedna dwójka, jedna jedynka
  5 -> 111221 -> jedna jedynka, jedna dwojka, dwie jedynki

spróbowac z iteratorem:
from itertools import groupby


numbers = '5555AAAsssWWWWaaa'

for key, value in groupby(numbers):
    print(key, list(value))
wyprodukuje:

5 [’5′, '5′, '5′, '5′]
A [’A’, 'A’, 'A’]
s [’s’, 's’, 's’]
W [’W’, 'W’, 'W’, 'W’]
a [’a’, 'a’, 'a’]

In [ ]:
def getFileIDsDigitSum(position):
  if len(position)<=1000:
    if (all(val<=54 and val>=1 for val in position)):
      x=[[1], [1, 1]]
      for i in range(1, max(position)-1):
        count=1
        for n in range (len(x[i])-1):
          if x[i][n]==x[i][n+1]:
            count+=1
          elif len(x)==i+2:
            x[i+1]=x[i+1]+[count, x[i][n]]
            count=1
            continue
          else:
            x=x+[[count, x[i][n]]]
            count=1
            continue
        if len(x)==i+2:
            x[i+1]=x[i+1]+[count, x[i][n+1]]
        else:
            x=x+[[count, x[i][n+1]]]

      for j in position:
        print(sum(x[j-1]))
    

In [ ]:
position = [1, 4, 11, 3]
getFileIDsDigitSum(position)

1
5
44
3


#Minimum transaction to equalize assets

In [ ]:
def equalize (assets):
  if len(assets)<=10**5 and len(assets)>=1:
    if (all(val<=10**9 and val>=0 for val in assets)):
      minTrans = 10**10
      Trans = 0
      for aim in range (max(assets)+1):
        for i in assets:
          Trans += abs(aim-i)
        if Trans<minTrans:
          minTrans = Trans
        Trans= 0
      return minTrans

In [ ]:
assets = [10, 20, 30, 40, 50, 51, 52, 53, 54, 55]
equalize (assets)

115

In [58]:
a=[-999, 45,-999, 5]
all(x!=-999 for x in a)


False

In [94]:
import numpy as np
a = np.array((2, 1))
b = np.array((3, 2))
dist = np.linalg.norm(b-a)
dist

1.4142135623730951

In [56]:
ind=np.where(np.array(a)!=-999)[0]

In [49]:
list(i)

[1, 3]

In [59]:

a =[a[i] for  i in np.where(np.array(a)!=-999)[0]]
a

[45, 5]

In [40]:
a

45

In [33]:
len(np.array(a))

4

In [95]:
np.isinf(float('inf'))

True

In [87]:
a = [-999, -999, -999, 4]
b = [-999, 55, 1, 3]

In [83]:
a-b

TypeError: ignored

In [88]:
a=np.array(a)
b=np.array(b)

In [89]:
a-b

array([    0, -1054, -1000,     1])

In [90]:
a=np.array(a)

In [91]:
a-b

array([    0, -1054, -1000,     1])

In [80]:
ind = np.where(np.array(a)!=-999)[0]
a =[a[i] for  i in ind ]
b =[b[i] for  i in ind]
ind = np.where(np.array(b)!=-999)[0]
a =[a[i] for  i in ind ]
b =[b[i] for  i in ind]

In [81]:
print(a)
print(b)

[]
[]


In [174]:
b = np.array([-999, 4, 1.2, 3])
a = np.array([2, 1, -999, -999])

In [175]:
import numpy as np


def augmented_euclidean_dist(a, b):
    # Write your code here.
    a=np.array(a)
    b=np.array(b)
    if len(a) == len(b):
        if any(x==-999 for x in a) or any(x==-999 for x in b):
            ind = np.where(np.array(a)!=-999)[0]
            a =[a[i] for  i in ind ]
            b =[b[i] for  i in ind]
            ind = np.where(np.array(b)!=-999)[0]
            a =[a[i] for  i in ind ]
            b =[b[i] for  i in ind]
            if len(a) < 2:
              return float('inf')   
            else:
              return np.linalg.norm(np.array(a)-np.array(b))
        else:
            return np.linalg.norm(np.array(a)-np.array(b))

In [162]:
len(a) == len(b)

True

In [163]:
any(x==-999 for x in a) or any(x==-999 for x in b)

True

In [165]:
ind = np.where(np.array(a)!=-999)[0]
a =[a[i] for  i in ind ]
b =[b[i] for  i in ind]
ind = np.where(np.array(b)!=-999)[0]
a =[a[i] for  i in ind ]
b =[b[i] for  i in ind]

In [166]:
a

[2, 1]

In [169]:
len(a) < 2

False

In [167]:
b

[5.0, 4.0]

In [176]:
x=augmented_euclidean_dist(a, b)
print(x)

inf


In [150]:
ind = np.where(np.array(a)!=-999)[0]
a =[a[i] for  i in ind ]
b =[b[i] for  i in ind]

In [151]:
ind = np.where(np.array(b)!=-999)[0]
a =[a[i] for  i in ind ]
b =[b[i] for  i in ind]

In [153]:
np.linalg.norm(np.array(a)-np.array(b))

4.242640687119285

In [152]:
np.array(a)-np.array(b)

array([-3., -3.])